# Generated by Django 2.2 on 2019-05-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Cliente',
        ),
    ]
